tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-u
    command: |
      # Community Edition
      sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c

      # Ultimate Edition
      #sudo docker run --rm -p 8887:8887 -v /workspace/template-jetbrains-intellij-idea:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-u