version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=rooma
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
  web:
    image: laurie/rooma
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db